@startuml

left to right direction
actor Usuario as U
rectangle "Casos de Uso - Informe Técnico" {

  usecase "Registrar Informe" as UC1
  usecase "Listar Informes" as UC2
  usecase "Actualizar Informe" as UC3
  usecase "Eliminar Informe" as UC4
    }
    U --> UC1
    U --> UC2
    U --> UC3
    U --> UC4


@enduml
